### ISSUE TITLE
Add logic to feature search

### ISSUE THREAD

**Issue by tanaes** [biocore/scikit-bio-rfcs#12]
Currently searching within metadata look for intersection of metadata values.

Many users are likely to want to search for collections of metadata values—for example, grabbing all of the features annotated as belonging to a set of genes in a particular pathway. 

It would be faster to include that OR logic in the query itself, rather than having to do separate searches for each of these genes. 

 :)

**Comment by jairideout** [comment]
@tanaes what API are you referring to in scikit-bio? Is this related to interval metadata? AFAIK we currently don't have an API to search metadata, it's just stored as a `dict`.

**Comment by tanaes** [comment]
Hey Jai, was meaning to make a feature request specifically wrt the
interval metadata, per a comment made in code review this morning. Not sure
I got the right place?

**Comment by jairideout** [comment]
This feature request probably makes sense as a comment on the [interval metadata pull request](https://github.com/biocore/scikit-bio/pull/1356), which is where that functionality is being implemented. Alternatively, if you anticipate this feature having larger impacts on the interval metadata design, and hence needing more extensive discussion from the community, feel free to open a pull request on this repo with your proposed changes to the [interval metadata RFC](https://github.com/biocore/scikit-bio-rfcs/blob/master/accepted/003-interval-metadata.md).

**Comment by josenavas** [comment]
@jairideout we were reviewing the code during a meeting and we decided that such functionality can be added later, but it is not critical to have it at this moment, hence the approach of adding an issue so we can keep track of it later, rather than adding as a comment in the interval metadata pull request. Does it make sense?

Based on this information, do you still think that the best approach is to open a PR against the interval metadata RFC or adding an issue in the scikit-bio repo?

**Comment by jairideout** [comment]
I think it makes sense to create an issue on the scikit-bio issue tracker since the change sounds like it can be made in a backwards-compatible way and won't have major impacts on the design presented in this RFC (please correct me if I am wrong). If the changes end up having larger impact we may ask someone to update the RFC with the new design (or create a new RFC with the proposed changes). For now it makes sense on the scikit-bio issue tracker until the interval metadata PR is merged (the issue could easily be forgotten here).
